services:
  backend:
    container_name: "${APP_NAME}-backend"
    image: "ghcr.io/2enter/${APP_NAME}-backend:latest"
    restart: unless-stopped
    volumes:
      - ./backend/db/storage:/app/backend/db/storage
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:3000"
    networks: [default, pg_net]
    user: "0:0"

networks:
  pg_net:
    external: true
