/*
 Generated by typeshare 1.13.2
*/

export enum CargoType {
	Water = "water",
	Spring = "spring",
	Stair = "stair",
	Star = "star",
	Cake = "cake",
	Diamond = "diamond",
}

export enum CargoStatus {
	Shipping = "shipping",
	Delivered = "delivered",
	Launched = "launched",
}

export interface Cargo {
	id: string;
	createdAt: Date;
	paintTime: number;
	type: CargoType;
	status: CargoStatus;
}

export interface CargoInput {
	paintTime: number;
	type: CargoType;
}

